USE [DigiBlogDB]
GO
ALTER DATABASE [DigiBlogDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DigiBlogDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DigiBlogDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DigiBlogDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DigiBlogDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [DigiBlogDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DigiBlogDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DigiBlogDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DigiBlogDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DigiBlogDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DigiBlogDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DigiBlogDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DigiBlogDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DigiBlogDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DigiBlogDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DigiBlogDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DigiBlogDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DigiBlogDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DigiBlogDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DigiBlogDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DigiBlogDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DigiBlogDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DigiBlogDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DigiBlogDB] SET  MULTI_USER 
GO
ALTER DATABASE [DigiBlogDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DigiBlogDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DigiBlogDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DigiBlogDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DigiBlogDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DigiBlogDB] SET QUERY_STORE = OFF
GO
USE [DigiBlogDB]
GO
/****** Object:  User [digiuser]    Script Date: 2.12.2020 20:06:20 ******/
CREATE USER [digiuser] FOR LOGIN [digiuser] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [digiuser]
GO
/****** Object:  Table [dbo].[Comment]    Script Date: 2.12.2020 20:06:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Comment](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PostId] [int] NOT NULL,
	[Description] [nvarchar](500) NOT NULL,
 CONSTRAINT [PK_Comment] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Post]    Script Date: 2.12.2020 20:06:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Post](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](100) NOT NULL,
	[SubTitle] [nvarchar](250) NULL,
	[Description] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Post] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 2.12.2020 20:06:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Email] [nvarchar](120) NOT NULL,
	[Password] [nvarchar](max) NOT NULL,
	[Token] [nvarchar](max) NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_User]    Script Date: 2.12.2020 20:06:20 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_User] ON [dbo].[User]
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Comment]  WITH CHECK ADD  CONSTRAINT [FK_Comment_Post] FOREIGN KEY([PostId])
REFERENCES [dbo].[Post] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Comment] CHECK CONSTRAINT [FK_Comment_Post]
GO
USE [master]
GO
ALTER DATABASE [DigiBlogDB] SET  READ_WRITE 
GO
  INSERT INTO [DigiBlogDB].[dbo].[User] (Email,Password) VALUES ('eneskartal117@gmail.com','BD15F635C9CB57E96347D8F73DD9A1A766E5ADB2C59F160416DF1F15F7706CA0')
  --Şifrenin Decrypted hali : digiturk2020
